/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientRouteImport } from './routes/client'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientBookingsRouteImport } from './routes/client.bookings'
import { Route as ClientProfileRouteImport } from './routes/client.profile'
import { Route as ClientWalletRouteImport } from './routes/client.wallet'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as PlayerIndexRouteImport } from './routes/player.index'
import { Route as PlayerEarningsRouteImport } from './routes/player.earnings'
import { Route as PlayerProfileRouteImport } from './routes/player.profile'
import { Route as PlayerScheduleRouteImport } from './routes/player.schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientBookingsRoute = ClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientWalletRoute = ClientWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ClientRoute,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerEarningsRoute = PlayerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerProfileRoute = PlayerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerScheduleRoute = PlayerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PlayerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/player': typeof PlayerRouteWithChildren
  '/client/bookings': typeof ClientBookingsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/wallet': typeof ClientWalletRoute
  '/match/$id': typeof MatchIdRoute
  '/player/earnings': typeof PlayerEarningsRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/schedule': typeof PlayerScheduleRoute
  '/client/': typeof ClientIndexRoute
  '/player/': typeof PlayerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client/bookings': typeof ClientBookingsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/wallet': typeof ClientWalletRoute
  '/match/$id': typeof MatchIdRoute
  '/player/earnings': typeof PlayerEarningsRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/schedule': typeof PlayerScheduleRoute
  '/client': typeof ClientIndexRoute
  '/player': typeof PlayerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/player': typeof PlayerRouteWithChildren
  '/client/bookings': typeof ClientBookingsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/wallet': typeof ClientWalletRoute
  '/match/$id': typeof MatchIdRoute
  '/player/earnings': typeof PlayerEarningsRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/schedule': typeof PlayerScheduleRoute
  '/client/': typeof ClientIndexRoute
  '/player/': typeof PlayerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/player'
    | '/client/bookings'
    | '/client/profile'
    | '/client/wallet'
    | '/match/$id'
    | '/player/earnings'
    | '/player/profile'
    | '/player/schedule'
    | '/client/'
    | '/player/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client/bookings'
    | '/client/profile'
    | '/client/wallet'
    | '/match/$id'
    | '/player/earnings'
    | '/player/profile'
    | '/player/schedule'
    | '/client'
    | '/player'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/player'
    | '/client/bookings'
    | '/client/profile'
    | '/client/wallet'
    | '/match/$id'
    | '/player/earnings'
    | '/player/profile'
    | '/player/schedule'
    | '/client/'
    | '/player/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  PlayerRoute: typeof PlayerRouteWithChildren
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/bookings': {
      id: '/client/bookings'
      path: '/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/wallet': {
      id: '/client/wallet'
      path: '/wallet'
      fullPath: '/client/wallet'
      preLoaderRoute: typeof ClientWalletRouteImport
      parentRoute: typeof ClientRoute
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/earnings': {
      id: '/player/earnings'
      path: '/earnings'
      fullPath: '/player/earnings'
      preLoaderRoute: typeof PlayerEarningsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/profile': {
      id: '/player/profile'
      path: '/profile'
      fullPath: '/player/profile'
      preLoaderRoute: typeof PlayerProfileRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/schedule': {
      id: '/player/schedule'
      path: '/schedule'
      fullPath: '/player/schedule'
      preLoaderRoute: typeof PlayerScheduleRouteImport
      parentRoute: typeof PlayerRoute
    }
  }
}

interface ClientRouteChildren {
  ClientBookingsRoute: typeof ClientBookingsRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientWalletRoute: typeof ClientWalletRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientBookingsRoute: ClientBookingsRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientWalletRoute: ClientWalletRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface PlayerRouteChildren {
  PlayerEarningsRoute: typeof PlayerEarningsRoute
  PlayerProfileRoute: typeof PlayerProfileRoute
  PlayerScheduleRoute: typeof PlayerScheduleRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerEarningsRoute: PlayerEarningsRoute,
  PlayerProfileRoute: PlayerProfileRoute,
  PlayerScheduleRoute: PlayerScheduleRoute,
  PlayerIndexRoute: PlayerIndexRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  PlayerRoute: PlayerRouteWithChildren,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
